//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17624
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50425.1
// 
namespace MonkeyLibs.Msdn {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mtpsFaultDetailType", Namespace="urn:msdn-com:public-content-syndication/2006/09/common")]
    internal partial class mtpsFaultDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eventIdField;
        
        private string sourceField;
        
        private string helpLinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string eventId {
            get {
                return this.eventIdField;
            }
            set {
                if ((object.ReferenceEquals(this.eventIdField, value) != true)) {
                    this.eventIdField = value;
                    this.RaisePropertyChanged("eventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        internal string source {
            get {
                return this.sourceField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceField, value) != true)) {
                    this.sourceField = value;
                    this.RaisePropertyChanged("source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        internal string helpLink {
            get {
                return this.helpLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.helpLinkField, value) != true)) {
                    this.helpLinkField = value;
                    this.RaisePropertyChanged("helpLink");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:msdn-com:public-content-syndication", ConfigurationName="Msdn.ContentServicePortType")]
    internal interface ContentServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:msdn-com:public-content-syndication/GetContent", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MonkeyLibs.Msdn.mtpsFaultDetailType), Action="urn:msdn-com:public-content-syndication/GetContent", Name="mtpsFaultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestedDocument[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(primary[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(image[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(common[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(feature[]))]
        System.Threading.Tasks.Task<MonkeyLibs.Msdn.GetContentResponse1> GetContentAsync(MonkeyLibs.Msdn.GetContentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:msdn-com:public-content-syndication/GetNavigationPaths", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MonkeyLibs.Msdn.mtpsFaultDetailType), Action="urn:msdn-com:public-content-syndication/GetNavigationPaths", Name="mtpsFaultDetail")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestedDocument[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(primary[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(image[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(common[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(feature[]))]
        System.Threading.Tasks.Task<MonkeyLibs.Msdn.GetNavigationPathsResponse1> GetNavigationPathsAsync(MonkeyLibs.Msdn.GetNavigationPathsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class getContentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentIdentifierField;
        
        private string localeField;
        
        private string versionField;
        
        private requestedDocument[] requestedDocumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string contentIdentifier {
            get {
                return this.contentIdentifierField;
            }
            set {
                this.contentIdentifierField = value;
                this.RaisePropertyChanged("contentIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=1)]
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=2)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public requestedDocument[] requestedDocuments {
            get {
                return this.requestedDocumentsField;
            }
            set {
                this.requestedDocumentsField = value;
                this.RaisePropertyChanged("requestedDocuments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class requestedDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string selectorField;
        
        private documentTypes typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string selector {
            get {
                return this.selectorField;
            }
            set {
                this.selectorField = value;
                this.RaisePropertyChanged("selector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public documentTypes type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:msdn-com:public-content-syndication")]
    public enum documentTypes {
        
        /// <remarks/>
        primary,
        
        /// <remarks/>
        common,
        
        /// <remarks/>
        image,
        
        /// <remarks/>
        feature,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class navigationPathNode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private bool isPhantomField;
        
        private bool isPhantomFieldSpecified;
        
        private navigationKey navigationNodeKeyField;
        
        private navigationKey contentNodeKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool isPhantom {
            get {
                return this.isPhantomField;
            }
            set {
                this.isPhantomField = value;
                this.RaisePropertyChanged("isPhantom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPhantomSpecified {
            get {
                return this.isPhantomFieldSpecified;
            }
            set {
                this.isPhantomFieldSpecified = value;
                this.RaisePropertyChanged("isPhantomSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public navigationKey navigationNodeKey {
            get {
                return this.navigationNodeKeyField;
            }
            set {
                this.navigationNodeKeyField = value;
                this.RaisePropertyChanged("navigationNodeKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public navigationKey contentNodeKey {
            get {
                return this.contentNodeKeyField;
            }
            set {
                this.contentNodeKeyField = value;
                this.RaisePropertyChanged("contentNodeKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class navigationKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentIdField;
        
        private string localeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=0)]
        public string contentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
                this.RaisePropertyChanged("contentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=1)]
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=2)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class navigationPath : object, System.ComponentModel.INotifyPropertyChanged {
        
        private navigationPathNode[] navigationPathNodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public navigationPathNode[] navigationPathNodes {
            get {
                return this.navigationPathNodesField;
            }
            set {
                this.navigationPathNodesField = value;
                this.RaisePropertyChanged("navigationPathNodes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:msdn-com:public-content-syndication/2006/09/common")]
    internal partial class appId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class availableVersionAndLocale : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string localeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=0)]
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mtpg-com:mtps/2004/1/primary")]
    internal partial class primary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.Linq.XElement anyField;
        
        private string primaryFormatField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.Linq.XElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="urn:mtpg-com:mtps/2004/1/primary/category")]
        public string primaryFormat {
            get {
                return this.primaryFormatField;
            }
            set {
                this.primaryFormatField = value;
                this.RaisePropertyChanged("primaryFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mtpg-com:mtps/2004/1/image")]
    internal partial class image : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string imageFormatField;
        
        private string locationField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="urn:mtpg-com:mtps/2004/1/image/category")]
        public string imageFormat {
            get {
                return this.imageFormatField;
            }
            set {
                this.imageFormatField = value;
                this.RaisePropertyChanged("imageFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mtpg-com:mtps/2004/1/common")]
    internal partial class common : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string commonFormatField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.Linq.XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="urn:mtpg-com:mtps/2004/1/common/category")]
        public string commonFormat {
            get {
                return this.commonFormatField;
            }
            set {
                this.commonFormatField = value;
                this.RaisePropertyChanged("commonFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mtpg-com:mtps/2004/1/feature")]
    public partial class feature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string featureFormatField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.Linq.XElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="urn:mtpg-com:mtps/2004/1/feature/category")]
        public string featureFormat {
            get {
                return this.featureFormatField;
            }
            set {
                this.featureFormatField = value;
                this.RaisePropertyChanged("featureFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class getContentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentIdField;
        
        private string contentGuidField;
        
        private string contentAliasField;
        
        private string localeField;
        
        private string versionField;
        
        private availableVersionAndLocale[] availableVersionsAndLocalesField;
        
        private primary[] primaryDocumentsField;
        
        private image[] imageDocumentsField;
        
        private common[] commonDocumentsField;
        
        private feature[] featureDocumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=0)]
        public string contentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
                this.RaisePropertyChanged("contentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=1)]
        public string contentGuid {
            get {
                return this.contentGuidField;
            }
            set {
                this.contentGuidField = value;
                this.RaisePropertyChanged("contentGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=2)]
        public string contentAlias {
            get {
                return this.contentAliasField;
            }
            set {
                this.contentAliasField = value;
                this.RaisePropertyChanged("contentAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=3)]
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:mtpg-com:mtps/2004/1/key", Order=4)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        internal availableVersionAndLocale[] availableVersionsAndLocales {
            get {
                return this.availableVersionsAndLocalesField;
            }
            set {
                this.availableVersionsAndLocalesField = value;
                this.RaisePropertyChanged("availableVersionsAndLocales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("primary", Namespace="urn:mtpg-com:mtps/2004/1/primary", IsNullable=false)]
        public primary[] primaryDocuments {
            get {
                return this.primaryDocumentsField;
            }
            set {
                this.primaryDocumentsField = value;
                this.RaisePropertyChanged("primaryDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("image", Namespace="urn:mtpg-com:mtps/2004/1/image", IsNullable=false)]
        public image[] imageDocuments {
            get {
                return this.imageDocumentsField;
            }
            set {
                this.imageDocumentsField = value;
                this.RaisePropertyChanged("imageDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("common", Namespace="urn:mtpg-com:mtps/2004/1/common", IsNullable=false)]
        public common[] commonDocuments {
            get {
                return this.commonDocumentsField;
            }
            set {
                this.commonDocumentsField = value;
                this.RaisePropertyChanged("commonDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("feature", Namespace="urn:mtpg-com:mtps/2004/1/feature", IsNullable=false)]
        public feature[] featureDocuments {
            get {
                return this.featureDocumentsField;
            }
            set {
                this.featureDocumentsField = value;
                this.RaisePropertyChanged("featureDocuments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetContentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:msdn-com:public-content-syndication", Order=0)]
        public MonkeyLibs.Msdn.getContentRequest getContentRequest;
        
        public GetContentRequest1() {
        }
        
        public GetContentRequest1(MonkeyLibs.Msdn.getContentRequest getContentRequest) {
            this.getContentRequest = getContentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetContentResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:msdn-com:public-content-syndication", Order=0)]
        public MonkeyLibs.Msdn.getContentResponse getContentResponse;
        
        public GetContentResponse1() {
        }
        
        public GetContentResponse1(MonkeyLibs.Msdn.getContentResponse getContentResponse) {
            this.getContentResponse = getContentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class getNavigationPathsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private navigationKey rootField;
        
        private navigationKey targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        internal navigationKey root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
                this.RaisePropertyChanged("root");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        internal navigationKey target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17624")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:msdn-com:public-content-syndication")]
    internal partial class getNavigationPathsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private navigationPath[] navigationPathsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        internal navigationPath[] navigationPaths {
            get {
                return this.navigationPathsField;
            }
            set {
                this.navigationPathsField = value;
                this.RaisePropertyChanged("navigationPaths");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetNavigationPathsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:msdn-com:public-content-syndication", Order=0)]
        public MonkeyLibs.Msdn.getNavigationPathsRequest getNavigationPathsRequest;
        
        public GetNavigationPathsRequest1() {
        }
        
        public GetNavigationPathsRequest1(MonkeyLibs.Msdn.getNavigationPathsRequest getNavigationPathsRequest) {
            this.getNavigationPathsRequest = getNavigationPathsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetNavigationPathsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:msdn-com:public-content-syndication", Order=0)]
        public MonkeyLibs.Msdn.getNavigationPathsResponse getNavigationPathsResponse;
        
        public GetNavigationPathsResponse1() {
        }
        
        public GetNavigationPathsResponse1(MonkeyLibs.Msdn.getNavigationPathsResponse getNavigationPathsResponse) {
            this.getNavigationPathsResponse = getNavigationPathsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ContentServicePortTypeChannel : MonkeyLibs.Msdn.ContentServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ContentServicePortTypeClient : System.ServiceModel.ClientBase<MonkeyLibs.Msdn.ContentServicePortType>, MonkeyLibs.Msdn.ContentServicePortType {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ContentServicePortTypeClient() : 
                base(ContentServicePortTypeClient.GetDefaultBinding(), ContentServicePortTypeClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.ContentService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContentServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ContentServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), ContentServicePortTypeClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContentServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ContentServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContentServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ContentServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContentServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MonkeyLibs.Msdn.GetContentResponse1> MonkeyLibs.Msdn.ContentServicePortType.GetContentAsync(MonkeyLibs.Msdn.GetContentRequest1 request) {
            return base.Channel.GetContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<MonkeyLibs.Msdn.GetContentResponse1> GetContentAsync(MonkeyLibs.Msdn.getContentRequest getContentRequest) {
            MonkeyLibs.Msdn.GetContentRequest1 inValue = new MonkeyLibs.Msdn.GetContentRequest1();
            inValue.getContentRequest = getContentRequest;
            return ((MonkeyLibs.Msdn.ContentServicePortType)(this)).GetContentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MonkeyLibs.Msdn.GetNavigationPathsResponse1> MonkeyLibs.Msdn.ContentServicePortType.GetNavigationPathsAsync(MonkeyLibs.Msdn.GetNavigationPathsRequest1 request) {
            return base.Channel.GetNavigationPathsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MonkeyLibs.Msdn.GetNavigationPathsResponse1> GetNavigationPathsAsync(MonkeyLibs.Msdn.getNavigationPathsRequest getNavigationPathsRequest) {
            MonkeyLibs.Msdn.GetNavigationPathsRequest1 inValue = new MonkeyLibs.Msdn.GetNavigationPathsRequest1();
            inValue.getNavigationPathsRequest = getNavigationPathsRequest;
            return ((MonkeyLibs.Msdn.ContentServicePortType)(this)).GetNavigationPathsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ContentService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ContentService)) {
                return new System.ServiceModel.EndpointAddress("http://services.msdn.microsoft.com/ContentServices/ContentService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ContentServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ContentService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ContentServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.ContentService);
        }
        
        public enum EndpointConfiguration {
            
            ContentService,
        }
    }
}
